version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: todo_backend
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: todo_frontend
    ports:
      - '3001:3001'
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend

volumes:
  postgres_data:
